Repository red-hat-storage/mcg-ms-console, pull requests merged in 2022-08, with the labels that each got.

#66 E2E: skip tests when required data does not exist.
  cypress/constants/tests.ts
  cypress/support.ts
  cypress/tests/data-source.spec.ts
  package.json
  yarn.lock
Labels: approved, lgtm

#61 fix: added some css padding to various screens
  packages/components/bucket-policy/bucket-policy.scss
  packages/components/dashboard/resource-providers-card/resource-providers-card.scss
  packages/components/dashboard/resource-providers-card/resource-providers-card.tsx
  packages/components/data-resource/data-resource.scss
Labels: approved, lgtm

#64 fix: reset the secret name on data source name change
  packages/components/data-resource/data-resource-create-form.tsx
  packages/components/data-resource/s3-endpoint-type.tsx
Labels: approved, lgtm

#72 fix: added the option to view cached data source in list page
  packages/components/resource-pages/data-resource-list-view.tsx
Labels: approved, lgtm

#63 fix: updated the text as per the ux diagram
  console-extensions.json
  cypress/tests/bucket-policy.spec.ts
  cypress/tests/object-bucket-claims.spec.ts
  cypress/views/mcg-ms-common.ts
  locales/en/plugin__mcg-ms-console.json
  packages/components/bucket-policy/bucket-policy-body.tsx
  packages/components/bucket-policy/create-bucket-policy.tsx
  packages/components/bucket-policy/data-resource-dropdowns.tsx
  packages/components/dashboard/dashboard.scss
  packages/components/dashboard/dashboard.tsx
  packages/components/dashboard/inventory-card/inventory-card.tsx
  packages/components/dashboard/status-card/status-card.tsx
  packages/components/data-resource/create-data-resource.tsx
  packages/components/data-resource/s3-endpoint-type.tsx
  packages/components/mcg/CreateObjectBucketClaim.tsx
  packages/components/mcg/ObjectBucket.tsx
  packages/components/mcg/ObjectBucketClaim.tsx
  packages/components/mcg/secret.tsx
  packages/components/modals/data-resource/data-resource-create-modal.tsx
  packages/components/modals/data-resource/modal-status.tsx
  packages/components/resource-pages/bucket-policy-details-page.tsx
  packages/components/resource-pages/bucket-policy-list-view.tsx
  packages/components/resource-pages/data-resource-list-view.tsx
  packages/constants/common.ts
  packages/models/noobaa.ts
  packages/utils/badges/badge.scss
  packages/utils/badges/service-preview.tsx
  packages/utils/list-page/list-page.tsx
  prow.sh
Labels: approved, lgtm

#68 build script fix: enforce production mode
  package.json
  webpack.config.ts
Labels: approved, lgtm

#74 Set default OBC NS to dedicated-admin for dedicated-admin user
  package.json
  packages/components/bucket-policy/bucket-policy-body.tsx
  packages/utils/badges/service-preview.tsx
Labels: approved

#77 CI E2E fixes
  ci/e2e/pre-hook.sh
  prow.sh
Labels: approved, lgtm

#75 UI: fix activity card alignment with resource prov. card
  packages/components/dashboard/activity-card/activity-card.scss
  packages/components/dashboard/dashboard.scss
Labels: approved, lgtm

#76 UI dev. deps: replace deprecated node-sass with dart-sass
  package.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#80 Introduce UI changes for osde2e
  cypress/constants/common.ts
  cypress/support/login.ts
Labels: lgtm

#83 E2E CI: set deploy env. vars from configmap/addon-env
  ci/e2e/pre-hook.sh
Labels: approved, lgtm

#82 Fallback to default values for Cypress login.
  cypress/support/login.ts
Labels: approved, lgtm

#89 Add dependabot config
  .github/dependabot.yml
Labels: approved, lgtm

#67 tests: inventory card + some refactoring of data source
  cypress/constants/tests.ts
  cypress/tests/data-source.spec.ts
  cypress/tests/inventory-card.spec.ts
  cypress/tests/resource-provider-card.spec.ts
  cypress/views/bucket-policies.ts
  cypress/views/data-resource.ts
  cypress/views/mcg-ms-common.ts
  locales/en/plugin__mcg-ms-console.json
  packages/components/dashboard/inventory-card/inventory-card.tsx
  packages/components/resource-pages/bucket-policy-list-view.tsx
Labels: approved, lgtm

#91 dependabot: monthly interval
  .github/dependabot.yml
Labels: approved, lgtm
