Repository red-hat-storage/mcg-ms-console, pull requests merged in 2022-07, with the labels that each got.

#45 E2E code cleanup
  cypress/support.ts
  cypress/support/login.ts
  cypress/support/selectors.ts
  e2e-ops.sh
  package.json
  packages/components/bucket-policy/bucket-policy-footer.tsx
  packages/components/modals/data-resource/modal-status.tsx
  packages/utils/details-page/DetailsPage.tsx
  packages/utils/error/Errors.tsx
  packages/utils/generics/NameValueEditor.tsx
  packages/utils/generics/link.tsx
  packages/utils/heading/page-heading.tsx
  prow.sh
  yarn.lock
Labels: approved, lgtm, ok-to-test

#48 Use ResourceDropdown component for Buckets page
  locales/en/plugin__mcg-ms-console.json
  packages/components/bucket-policy/bucket-policy-body.tsx
  packages/components/bucket-policy/bucket-policy.scss
  packages/components/data-resource/data-resource-create-form.tsx
  packages/components/data-resource/s3-endpoint-type.tsx
  packages/components/mcg/CreateObjectBucketClaim.tsx
Labels: approved, lgtm

#51 fix: on-going activity skeletion issue
  packages/components/dashboard/activity-card/activity-card.tsx
Labels: approved, lgtm

#46 E2E CI fixes & Object Bucket Claim tests
  Dockerfile.ci
  cypress/.eslintrc.js
  cypress/support/login.ts
  cypress/support/selectors.ts
  cypress/tests/object-bucket-claims.spec.ts
  cypress/tests/t.spec.ts
  e2e-ops.sh
  http-server.sh
  packages/components/mcg/CreateObjectBucketClaim.tsx
  packages/utils/dropdown/ResourceDropdown.tsx
  packages/utils/modals/DeleteModal.tsx
  prow.sh
Labels: approved, lgtm

#54 Fix resource provider card
  packages/components/dashboard/dashboard.tsx
  packages/components/dashboard/resource-providers-card/resource-providers-card-item.tsx
  packages/components/dashboard/resource-providers-card/resource-providers-card.scss
  packages/components/dashboard/resource-providers-card/resource-providers-card.tsx
  packages/components/data-resource/data-resource-create-form.tsx
  packages/constants/index.ts
  packages/constants/noobaa.ts
  packages/constants/providers.ts
  packages/utils/index.ts
  packages/utils/noobaa-utils.ts
  packages/utils/providers.ts
Labels: approved, lgtm

#55 fix: minor css fixed along to maintain uniformity
  packages/components/dashboard/activity-card/activity-card.scss
  packages/components/dashboard/dashboard.scss
  packages/components/data-resource/data-resource.scss
  packages/components/data-resource/s3-endpoint-type.tsx
Labels: approved, lgtm

#50 tests: status card of admin dashboard
  cypress/constants/common.ts
  cypress/consts.ts
  cypress/plugin.js
  cypress/support/login.ts
  cypress/support/selectors.ts
  cypress/support/views.ts
  cypress/tests/status-card.spec.ts
  cypress/views/mcg-ms-common.ts
  packages/utils/dashboard/status-card/HealthItem.tsx
  packages/utils/status/icons.tsx
Labels: approved, lgtm

#57 Buckets page cypress tests
  cypress/constants/common.ts
  cypress/constants/tests.ts
  cypress/mocks/data-source.ts
  cypress/tests/bucket-policy.spec.ts
  cypress/tests/object-bucket-claims.spec.ts
  cypress/tests/status-card.spec.ts
  cypress/views/common.ts
  cypress/views/mcg-ms-common.ts
  cypress/views/pvc.ts
  e2e-ops.sh
  packages/components/bucket-policy/bucket-policy-body.tsx
  packages/components/bucket-policy/data-resource-dropdowns.tsx
  packages/components/resource-pages/ResourcePopOver.tsx
  packages/components/resource-pages/bucket-policy-list-view.tsx
  packages/utils/generics/resource-link.tsx
  packages/utils/kebab/kebab.tsx
  packages/utils/modals/DeleteModal.tsx
Labels: approved, lgtm

#59 Missing i18n error
  packages/components/bucket-policy/bucket-policy-body.tsx
  packages/components/bucket-policy/bucket-policy-footer.tsx
  packages/components/bucket-policy/create-bucket-policy.tsx
  packages/components/bucket-policy/data-resource-dropdowns.tsx
  packages/components/dashboard/activity-card/activity-card.tsx
  packages/components/dashboard/activity-card/data-resiliency-activity/data-resiliency-activity.tsx
  packages/components/dashboard/dashboard.tsx
  packages/components/dashboard/details-card/details-card.tsx
  packages/components/dashboard/inventory-card/inventory-card.tsx
  packages/components/dashboard/resource-providers-card/resource-providers-card.tsx
  packages/components/dashboard/status-card/status-card.tsx
  packages/components/data-resource/create-data-resource.tsx
  packages/components/data-resource/data-resource-create-form.tsx
  packages/components/data-resource/s3-endpoint-type.tsx
  packages/components/mcg/CreateObjectBucketClaim.tsx
  packages/components/mcg/ObjectBucket.tsx
  packages/components/mcg/ObjectBucketClaim.tsx
  packages/components/mcg/secret.tsx
  packages/components/modals/attach-deployment/attach-deployment-obc-modal.tsx
  packages/components/modals/data-resource/data-resource-create-modal.tsx
  packages/components/modals/data-resource/modal-status.tsx
  packages/components/resource-pages/CommonDetails.tsx
  packages/components/resource-pages/Providers.tsx
  packages/components/resource-pages/ResourcePopOver.tsx
  packages/components/resource-pages/bucket-policy-details-page.tsx
  packages/components/resource-pages/bucket-policy-list-view.tsx
  packages/components/resource-pages/data-resource-details-page.tsx
  packages/components/resource-pages/data-resource-list-view.tsx
  packages/utils/dashboard/data-resiliency/data-resiliency-activity.tsx
  packages/utils/dashboard/status-card/HealthItem.tsx
  packages/utils/details-page/Conditions.tsx
  packages/utils/details-page/DetailsPage.tsx
  packages/utils/details-page/owner-references.tsx
  packages/utils/dropdown/GenericDropdown.tsx
  packages/utils/dropdown/ResourceDropdown.tsx
  packages/utils/dropdown/StaticDropdown.tsx
  packages/utils/error/Errors.tsx
  packages/utils/generics/ButtonBar.tsx
  packages/utils/generics/NameValueEditor.tsx
  packages/utils/generics/SecretValue.tsx
  packages/utils/generics/copy-to-clipboard.tsx
  packages/utils/generics/link.tsx
  packages/utils/generics/promise-component.tsx
  packages/utils/generics/status-box.tsx
  packages/utils/hooks/useCustomTranslationHook.ts
  packages/utils/kebab/kebab.tsx
  packages/utils/list-page/list-page.tsx
  packages/utils/modals/DeleteModal.tsx
  packages/utils/modals/EditAnnotations.tsx
  packages/utils/modals/EditLabelModal.tsx
  packages/utils/noobaa-utils.ts
  packages/utils/status/statuses.tsx
Labels: approved

#58 tests: data source creation which won't go to ready state
  cypress/constants/tests.ts
  cypress/support/selectors.ts
  cypress/tests/data-source.spec.ts
  cypress/tests/status-card.spec.ts
  cypress/views/data-resource.ts
  cypress/views/mcg-ms-common.ts
  packages/components/data-resource/data-resource-create-form.tsx
  packages/components/data-resource/s3-endpoint-type.tsx
  packages/components/resource-pages/data-resource-details-page.tsx
  packages/components/resource-pages/data-resource-list-view.tsx
  packages/utils/dropdown/StaticDropdown.tsx
  packages/utils/kebab/kebab.tsx
Labels: approved, lgtm

#60 tests: resource providers card of admin dashboard
  cypress/constants/tests.ts
  cypress/mocks/data-source.ts
  cypress/tests/bucket-policy.spec.ts
  cypress/tests/resource-provider-card.spec.ts
  packages/components/dashboard/resource-providers-card/resource-providers-card.tsx
Labels: approved, lgtm, ok-to-test

#62 E2E CI hooks: create AWS bucket for Data Source testing
  .env.example
  .gitignore
  README.md
  ci/e2e/aws-hooks.ts
  ci/e2e/pre-hook.sh
  cypress/constants/tests.ts
  cypress/plugin.js
  cypress/tests/data-source.spec.ts
  package.json
  prow.sh
  yarn.lock
Labels: approved, lgtm
